FROM node:latest

RUN mkdir /srv/rest-api-sejutacita
WORKDIR /srv/rest-api-sejutacita

ADD package.json /srv/rest-api-sejutacita
RUN npm install

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

RUN npm install -g nodemon

EXPOSE 4501
CMD /wait && nodemon app.js